name: Update MatrixV1 on Release

on:
  release:
    types: [published]

jobs:
  update-matrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.tag_name }}

    - name: Set version
      run: |
        echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
        cat $GITHUB_ENV  # Debugging: Zeigt, ob VERSION wirklich gesetzt wurde

    - name: Update MatrixV1.PS1
      run: |
        curl -L -o MatrixV1.PS1 https://github.com/MetoRizz/Matrix-Game/releases/download/${{ github.event.release.tag_name }}/Matrix.Game.${{ github.event.release.tag_name }}.ps1
        echo "# Matrix Game Version $VERSION" >> MatrixV1.PS1

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add MatrixV1.PS1
        git commit -m "Update MatrixV1.PS1 to version $VERSION"
        git push origin HEAD:main
