name: Update MatrixV1 on Release

on:
  release:
    types: [published]

jobs:
  update-matrix:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: MatrixGameV1.2.1

    - name: Set version
      run: echo "VERSION=MatrixGameV1.2.1" >> $GITHUB_ENV

    - name: Update MatrixV1.PS1
      run: |
        echo "# Matrix Game Version ${{ env.VERSION }}" > MatrixV1.PS1
        cat MatrixV1.PS1

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add MatrixV1.PS1
        git commit -m "Update MatrixV1.PS1 to version ${{ env.VERSION }}"
        git push origin HEAD:main
